Write programs in Python using NumPy library to do the following:
    
a. Compute the mean, standard deviation, and variance of a two dimensional random integer array
along the second axis.

b. Get the indices of the sorted elements of a given array.

a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data
type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of
these elements in three separate arrays.



In [2]:
import numpy as np

In [3]:
#part a
arr = np.random.randint(1,50,(4,6))
arr

array([[17, 20, 31, 12, 16, 10],
       [44, 22, 32, 42, 30,  6],
       [49, 46, 33,  6,  3, 14],
       [34, 39, 35, 17, 29, 20]])

In [4]:
#along the second axis
#Mean
print('Mean of the array: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation of the array: ',arr.std(axis=1))
#variance
print('Variance of the array: ',arr.var(axis=1))

Mean of the array:  [17.66666667 29.33333333 25.16666667 29.        ]
Standard Deviation of the array:  [ 6.79869268 12.78888406 18.46994556  8.02080628]
Variance of the array:  [ 46.22222222 163.55555556 341.13888889  64.33333333]


In [5]:
#part b
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
#arr1
print("Sorted array: ",np.sort(arr1))
print("Indices of the sorted elements of a given array: ",np.argsort(arr1))

Sorted array:  [ 8 22 24 33 41 46 48 56 78 91]
Indices of the sorted elements of a given array:  [8 2 6 9 3 7 1 0 4 5]


In [7]:
#part c
m = int(input('Enter the number of rows(m): '))
n = int(input('Enter the number of columns(n): '))
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
print('Type: ',type(arr2))
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

Enter the number of rows(m):  2
Enter the number of columns(n):  3


[[ 6 77 89]
 [55 43 24]]
Shape:  (2, 3)
Type:  <class 'numpy.ndarray'>
Data Type:  int32
After reshaping: 
 [[ 6 77]
 [89 55]
 [43 24]]
New Shape:  (3, 2)


In [8]:
#part D
x = np.array([1, 0, 3, 4])
print("ORIGINAL ARRAY ::-> ",x)
print("\nTest if none of the elements of the said array is zero ::-> ", np.all(x))

res = np.where(x == 0)[0]
print("The index of the  zero elements is :: ",res)


x = np.array([1, 0, 0, 3, 2, 0])
print("\n")
print("\nORIGINAL ARRAY ::-> ",x)
print("\nTest whether any of the elements of a given array is non-zero ::",np.any(x))
res = np.where(x != 0)[0]
print("The index of the non- zero elements is :: ",res)
x = np.array([0, 0, 0, 0])


a = np.array([1, 0, np.nan, 3, np.nan])
print("\n")
print("\nORIGINAL ARRAY ::-> ",a)
print("\nTest element-wise for NaN :: ",np.isnan(a))

res = np.where(np.isnan(a) == True)[0]
print("The index of the  zero elements is :: ",res)

ORIGINAL ARRAY ::->  [1 0 3 4]

Test if none of the elements of the said array is zero ::->  False
The index of the  zero elements is ::  [1]



ORIGINAL ARRAY ::->  [1 0 0 3 2 0]

Test whether any of the elements of a given array is non-zero :: True
The index of the non- zero elements is ::  [0 3 4]



ORIGINAL ARRAY ::->  [ 1.  0. nan  3. nan]

Test element-wise for NaN ::  [False False  True False  True]
The index of the  zero elements is ::  [2 4]
